apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: {{ .Values.namespace }}

spec:
  # replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          envFrom:
            - configMapRef:
                name: backend-config

          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.backend.readiness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.backend.liveness.path }}
              port: {{ .Values.backend.containerPort }}
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: {{ .Values.resources.backend.requests.cpu }}
              memory: {{ .Values.resources.backend.requests.memory }}

            limits:
              cpu: {{ .Values.resources.backend.limits.cpu }}
              memory: {{ .Values.resources.backend.limits.memory }}
