apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.backend.config.port }}"
  MONGO_URI: "{{ .Values.backend.config.mongoUri }}"