apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

        ports:
        - containerPort: {{ .Values.frontend.containerPort }}

        resources:
          requests:
            cpu: {{ .Values.resources.frontend.requests.cpu }}
            memory: {{ .Values.resources.frontend.requests.memory }}

          limits:
            cpu: {{ .Values.resources.frontend.limits.cpu }}
            memory: {{ .Values.resources.frontend.limits.memory }}