apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-ingress
  namespace: {{ .Values.namespace }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
  - host: {{ .Values.ingress.host }}

    http:
      paths:

      - path: /
        pathType: Prefix

        backend:
          service:
            name: {{ .Values.ingress.frontend.serviceName}}
            port:
              number: {{  .Values.ingress.frontend.servicePort }}

      - path: /api
        pathType: Prefix

        backend:
          service:
            name: {{ .Values.ingress.backend.serviceName }}
            port:
              number: {{ .Values.ingress.backend.servicePort }}