apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mongo.service.type }}
  selector:
    app: mongo
  ports:
  - port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.containerPort }}