name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:
      - self-hosted
      - Windows
      - X64

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v6

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      ####################################################
      # Backend
      ################################################

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Test Backend
        working-directory: backend
        run: npm test --if-present

      ####################################################
      # Frontend
      #####################################################

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Test Frontend
        working-directory: frontend
        run: npm test --if-present

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      ##############################################
      # Capture the GIT SHA
      ##############################################

      - name: Set Image Tag
        shell: powershell
        run: |
          $sha = "${{ github.sha }}".Substring(0,7)
          "IMAGE_TAG=$sha" >> $env:GITHUB_ENV

      ####################################################
      # Docker Build
      ####################################################

      - name: Build Backend Docker Image
        run: docker build -t savvydhar/backend:${{ env.IMAGE_TAG }} ./backend

      - name: Build Frontend Docker Image
        run: docker build -t savvydhar/frontend:${{ env.IMAGE_TAG }} ./frontend

      ####################################################
      # Docker Login
      ####################################################

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      ####################################################
      # Docker Push
      ####################################################

      - name: Push Backend Image
        run: docker push savvydhar/backend:${{ env.IMAGE_TAG }}

      - name: Push Frontend Image
        run: docker push savvydhar/frontend:${{ env.IMAGE_TAG }}

      #####################################################
      # Kubernetes Deployment
      #####################################################

      - name: Verify kubectl
        run: |
          kubectl version --client
          kubectl get nodes
          kubectl get deployments -n notes-app

      
      ####################################################
      # Kubernetes Deployment
      ####################################################

      - name: Deploy to Kubernetes
        shell: powershell
        run: |
          .\scripts\deploy.ps1 `
            -ImageTag "${{ env.IMAGE_TAG }}"
